local sub = require( 'ltest' )
print( sub.getclip() )
local json = loadfile("json.lua")()
print( json.encode({ 1, 2, 3, { x = 10 } }) )
sub.process_json( json.encode({ 1, 2, 3, { x = 10 } }) )
print( arg )
print( arg[0] )
print (#arg)
print( arg[1] )
print( arg[2] )
print( arg[3] )
